apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mmpl-production
  name: memcached-deployment
spec:
  selector:
    matchLabels:
      app: memcached
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: memcached
    spec: # pod spec
      containers:
        - name: memcached
          image: memcached:latest
          ports:
            - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  namespace: mmpl-production
  name: memcached-service
spec:
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
  selector:
    app: memcached
