apiVersion: v1
kind: Namespace
metadata:
  name: mmpl-production
  labels:
    name: mmpl-production
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-prod
  namespace: mmpl-production
spec:
  acme:
    email: mmpl.production@systemiphus.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: mmpl-production-ssl-certificate
    solvers:
      - http01:
          ingress:
            class: nginx
