apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mmpl-production
  name: tendenci-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
