apiVersion: v1
kind: Service
metadata:
  name: mmpl-do-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: mmpl-do-web-template
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmpl-do-deployment
spec:
  selector:
    matchLabels:
      app: mmpl-do-web-template
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: mmpl-do-web-template
    spec: # pod spec
      containers:
        - name: mmpl-do-web
          image: benjiboi214/mmpl-do:cicd_test # image we pushed
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mmpl-do-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "test.mmpl.bennyda.ninja"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mmpl-do-service
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: benjiboi214@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: mmpl-do-issuer-staging
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production
# spec:
#   acme:
#     # You must replace this email address with your own.
#     # Let's Encrypt will use this to contact you about expiring
#     # certificates, and issues related to your account.
#     email: benjiboi214@gmail.com
#     server: https://acme-v02.api.letsencrypt.org/directory
#     preferredChain: "ISRG Root X1"
#     privateKeySecretRef:
#       # Secret resource that will be used to store the account's private key.
#       name: mmpl-do-issuer-production
#     # Add a single challenge solver, HTTP01 using nginx
#     solvers:
#       - http01:
#           ingress:
#             class: nginx
