apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mmpl-do
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: mmpl-do
    spec:     # pod spec                  
      containers: 
      - name: mmpl-do
        image: benjiboi214/mmpl-do:cicd_test # image we pushed
        ports:
        - containerPort: 3000