export const historyDir = [
  {
    reference: 'winter-champions',
    label: 'Winter Champions',
    href: 'winter-champions/',
    parent: 'history',
    imageRef: ['media/mmpl-winter-splash.jpg']
  },
  {
    reference: 'summer-champions',
    label: 'Summer Champions',
    href: 'summer-champions/',
    parent: 'history',
    imageRef: ['media/mmpl-summer-splash.jpg']
  },
];

export const winterHistory = [
  {
    reference: 'winter-premier',
    href: 'winter-premier/',
    label: 'Premier',
    icon: 'fa-battery-full',
    menuSettings: {
      header: true,
      footer: false
    },
    description:
      'Historical winners of the MMPL Winter season in the Premier Division.',
    history: [
      {
        season: 2016,
        champion: '',
        runnersup: '',
        mvp: 'Ash Manocha',
        mvpTeam: 'Wombats',
        mvpPlayed: 71,
        mvpWon: 50,
        mvpLost: 21,
      },
      {
        season: 2015,
        champion: 'Baize Invaders',
        runnersup: 'Westerners',
        mvp: 'Rick Bell',
        mvpTeam: 'Baize Invaders',
        mvpPlayed: 56,
        mvpWon: 42,
        mvpLost: 14,
      },
      {
        season: 2014,
        champion: 'Allies',
        runnersup: 'Westerners',
        mvp: 'Rick Bell',
        mvpTeam: 'Allies',
        mvpPlayed: 90,
        mvpWon: 66,
        mvpLost: 24,
      },
      {
        season: 2013,
        champion: 'Allies United',
        runnersup: 'AK8',
        mvp: 'James Mifsud',
        mvpTeam: 'AK8',
        mvpPlayed: 94,
        mvpWon: 73,
        mvpLost: 21,
      },
      {
        season: 2012,
        champion: 'Westerners',
        runnersup: 'Wild Colonials',
        mvp: 'James Mifsud',
        mvpTeam: 'Princes',
        mvpPlayed: 72,
        mvpWon: 60,
        mvpLost: 12,
      },
      {
        season: 2011,
        champion: '59 Bangers',
        runnersup: 'Westerners',
        mvp: 'Peter Butterworth',
        mvpTeam: '59 Bangers',
        mvpPlayed: 60,
        mvpWon: 46,
        mvpLost: 14,
      },
      {
        season: 2010,
        champion: '59Bangers',
        runnersup: 'Westerners',
        mvp: 'Steve Tran',
        mvpTeam: 'Westerners',
        mvpPlayed: 60,
        mvpWon: 49,
        mvpLost: 11,
      },
      {
        season: 2009,
        champion: 'The 59\'ers',
        runnersup: 'Masters',
        mvp: 'James Mifsud',
        mvpTeam: 'The 59\'ers',
        mvpPlayed: 64,
        mvpWon: 53,
        mvpLost: 11,
      },
      {
        season: 2008,
        champion: 'Westerners',
        runnersup: 'Wild Colonials',
        mvp: 'James Mifsud',
        mvpTeam: 'The 59\'ers',
        mvpPlayed: 68,
        mvpWon: 53,
        mvpLost: 15,
      },
      {
        season: 2007,
        champion: 'Wild Colonials',
        runnersup: 'Westerners',
        mvp: 'Ben Nunan',
        mvpTeam: 'Legendary Bangers',
        mvpPlayed: 73,
        mvpWon: 62,
        mvpLost: 11,
      },
      {
        season: 2006,
        champion: 'Westerners',
        runnersup: 'Stingo Cannons',
        mvp: 'Paul Brewer',
        mvpTeam: 'Stingo Cannons',
        mvpPlayed: 73,
        mvpWon: 56,
        mvpLost: 17,
      },
      {
        season: 2005,
        champion: 'Breakers',
        runnersup: 'Bedford Bangers',
        mvp: 'Ben Nunan',
        mvpTeam: 'Bedford Bangers',
        mvpPlayed: 61,
        mvpWon: 54,
        mvpLost: 7,
      },
      {
        season: 2004,
        champion: 'Bedford Bangers',
        runnersup: 'The Max Cowboys',
        mvp: 'Jim Benis',
        mvpTeam: 'The Max Cowboys',
        mvpPlayed: 71,
        mvpWon: 54,
        mvpLost: 17,
      },
      {
        season: 2003,
        champion: 'Comics Lounge Growlers',
        runnersup: 'Richmond Cowboys',
        mvp: 'Ben Nunan',
        mvpTeam: 'The Growlers',
        mvpPlayed: 48,
        mvpWon: 43,
        mvpLost: 5,
      },
      {
        season: 2002,
        champion: 'Waterside Cannons',
        runnersup: 'The Nash Hotel',
        mvp: 'Brett Dorrington',
        mvpTeam: 'Waterside Cannons',
        mvpPlayed: 56,
        mvpWon: 40,
        mvpLost: 16,
      },
      {
        season: 2001,
        champion: 'The Nash Hotel',
        runnersup: 'Legends',
        mvp: 'Russ Nicholson',
        mvpTeam: 'Bush Inn Assassins',
        mvpPlayed: 65,
        mvpWon: 46,
        mvpLost: 19,
      },
      {
        season: 2000,
        champion: 'Clare Castle Hotel',
        runnersup: 'Waterside Cannons',
        mvp: 'Steve Tran',
        mvpTeam: 'Clare Castle',
        mvpPlayed: 66,
        mvpWon: 47,
        mvpLost: 19,
      },
      {
        season: 1999,
        champion: 'PoW Wanderers',
        runnersup: 'Clare Castle Hotel',
        mvp: 'Steve Tran',
        mvpTeam: 'Clare Castle',
        mvpPlayed: 57,
        mvpWon: 43,
        mvpLost: 14,
      },
      {
        season: 1998,
        champion: 'PoW Wanderers',
        runnersup: 'Richmond Cowboys',
        mvp: 'R Schmidt &',
        mvpTeam: 'No mvp records kept before 1999',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1998,
        champion: '',
        runnersup: '',
        mvp: 'Kjell Johansson',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1997,
        champion: 'Richmond Cowboys',
        runnersup: 'Harp Of Erin Hotel',
        mvp: 'Greg Webb &',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1997,
        champion: '',
        runnersup: '',
        mvp: 'W Klein',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1996,
        champion: 'Wanderers',
        runnersup: 'Richmond Cowboys',
        mvp: 'Des Shattock',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1995,
        champion: 'Richmond Cowboys',
        runnersup: 'Wanderers',
        mvp: 'Des Shattock',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1994,
        champion: 'Wanderers',
        runnersup: 'Great Britain Hotel',
        mvp: 'D Greening',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1993,
        champion: 'Royston Hotel',
        runnersup: 'Harp Of Erin Hotel',
        mvp: 'W Tolchard',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1992,
        champion: 'Royal Oak Hotel',
        runnersup: 'Harp Of Erin Hotel',
        mvp: 'Chris Habel',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1991,
        champion: 'Prince Of Wales Hotel',
        runnersup: 'Royal Oak Hotel',
        mvp: 'P Walker',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1990,
        champion: 'Clifton Hotel',
        runnersup: 'Whitehorse Hotel',
        mvp: 'G Mead',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1989,
        champion: 'Whitehorse Hotel',
        runnersup: 'Vine Hotel',
        mvp: 'Des Shattock',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1988,
        champion: 'Beehive Hotel',
        runnersup: 'Whitehorse Hotel',
        mvp: 'Dennis Brady',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1987,
        champion: 'Whitehorse Hotel',
        runnersup: 'Beehive Hotel',
        mvp: 'Cranne Wrigley',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1986,
        champion: 'Beehive Hotel',
        runnersup: 'National Hotel',
        mvp: 'Des Shattock',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1985,
        champion: 'National Hotel',
        runnersup: 'Whitehorse Hotel',
        mvp: 'n.k.',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1984,
        champion: 'National Hotel',
        runnersup: 'Glenferrie Hotel',
        mvp: 'J Vickery',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 1983,
        champion: 'No competition was held in the inaugural season',
        runnersup: '',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
    ],
  },
  {
    reference: 'winter-div-1',
    href: 'winter-div-1/',
    label: 'Division 1',
    icon: 'fa-battery-three-quarters',
    menuSettings: {
      header: true,
      footer: false
    },
    description:
      'Historical winners of the MMPL Winter season in the First Division.',
    history: [
      {
        season: 2016,
        champion: '',
        runnersup: '',
        mvp: 'Shane Fell',
        mvpTeam: 'Hotham Gold',
        mvpPlayed: 65,
        mvpWon: 55,
        mvpLost: 10,
      },
      {
        season: 2015,
        champion: 'Quarry Cannons',
        runnersup: 'Towering Inferno',
        mvp: 'Ash Manocha',
        mvpTeam: 'The Wombats',
        mvpPlayed: 71,
        mvpWon: 50,
        mvpLost: 21,
      },
      {
        season: 2014,
        champion: 'Nomads',
        runnersup: 'The Wombats',
        mvp: 'Ash Manocha',
        mvpTeam: 'The Wombats',
        mvpPlayed: 72,
        mvpWon: 52,
        mvpLost: 20,
      },
      {
        season: 2013,
        champion: 'Sharks',
        runnersup: 'Towering Inferno 1',
        mvp: 'Glenn Croese',
        mvpTeam: 'Towering Infernos',
        mvpPlayed: 69,
        mvpWon: 51,
        mvpLost: 18,
      },
      {
        season: 2012,
        champion: 'Dark Horses',
        runnersup: 'Baize Invaders',
        mvp: 'Peter Pezzimenti',
        mvpTeam: 'Baize Invaders',
        mvpPlayed: 70,
        mvpWon: 57,
        mvpLost: 13,
      },
      {
        season: 2011,
        champion: 'The Wombats',
        runnersup: 'Royal Park Tramways',
        mvp: 'Matt Purtell',
        mvpTeam: 'The Wombats',
        mvpPlayed: 62,
        mvpWon: 49,
        mvpLost: 13,
      },
      {
        season: 2010,
        champion: '(Towering Infernos v Crown 1)',
        runnersup: '',
        mvp: 'Robin Saab',
        mvpTeam: 'Crown 1',
        mvpPlayed: 72,
        mvpWon: 54,
        mvpLost: 18,
      },
      {
        season: 2009,
        champion: 'Masters 2',
        runnersup: 'Fitzroy Punters',
        mvp: 'Dave Kelly',
        mvpTeam: 'RM Wombats',
        mvpPlayed: 62,
        mvpWon: 48,
        mvpLost: 14,
      },
      {
        season: 2008,
        champion: 'Tang Station',
        runnersup: 'British Crown 1',
        mvp: 'Greg Nash',
        mvpTeam: 'Tang Station',
        mvpPlayed: 66,
        mvpWon: 53,
        mvpLost: 13,
      },
      {
        season: 2007,
        champion: 'FVPunters',
        runnersup: 'Nash 1',
        mvp: 'Angelo Butera',
        mvpTeam: 'The Bafflers',
        mvpPlayed: 85,
        mvpWon: 61,
        mvpLost: 24,
      },
      {
        season: 2006,
        champion: 'The Nash Hotel',
        runnersup: 'Rochester Punters',
        mvp: 'Suranga Senadipathy',
        mvpTeam: 'Harp Of Erin',
        mvpPlayed: 56,
        mvpWon: 39,
        mvpLost: 17,
      },
      {
        season: 2005,
        champion: 'Towering Inferno',
        runnersup: 'Rochester Punters',
        mvp: 'Michael Pryor',
        mvpTeam: 'Tramway',
        mvpPlayed: 54,
        mvpWon: 39,
        mvpLost: 15,
      },
      {
        season: 2004,
        champion: 'Harp Of Erin',
        runnersup: 'Royston Wanderers',
        mvp: 'Mike Goodwin',
        mvpTeam: 'Royston Wanderers',
        mvpPlayed: 70,
        mvpWon: 52,
        mvpLost: 18,
      },
      {
        season: 2003,
        champion: 'Waterside Wombats',
        runnersup: 'The Nash Hotel',
        mvp: 'Peter Gaskell',
        mvpTeam: 'Harp Of Erin A',
        mvpPlayed: 46,
        mvpWon: 38,
        mvpLost: 8,
      },
      {
        season: 2002,
        champion: 'Union Club Dispossessed',
        runnersup: 'Legends Bandits',
        mvp: 'Mike Goodwin',
        mvpTeam: 'Legends Bandits',
        mvpPlayed: 72,
        mvpWon: 52,
        mvpLost: 20,
      },
      {
        season: 2001,
        champion: 'The Bush Inn Assassins',
        runnersup: 'Punters Club Dispossessed',
        mvp: 'Brendon Dominguez',
        mvpTeam: 'Tramway Hotel',
        mvpPlayed: 62,
        mvpWon: 47,
        mvpLost: 15,
      },
      {
        season: 2000,
        champion: 'The Cue Masters',
        runnersup: 'The Bush Inn',
        mvp: 'Jonathon Thorpe',
        mvpTeam: 'Rising Sun',
        mvpPlayed: 54,
        mvpWon: 41,
        mvpLost: 13,
      },
      {
        season: 1999,
        champion: 'Waterside Mariners',
        runnersup: 'PoW Wanderers',
        mvp: 'Kjell Johansson (Nth) &',
        mvpTeam: 'Beehive Stingers',
        mvpPlayed: 64,
        mvpWon: 47,
        mvpLost: 17,
      },
      {
        season: 1999,
        champion: '',
        runnersup: '',
        mvp: 'Jonathon Thorpe (Sth)',
        mvpTeam: 'Rising Sun B',
        mvpPlayed: 62,
        mvpWon: 47,
        mvpLost: 15,
      },
      {
        season: 1998,
        champion: 'No 1st Division before Winter 1999',
        runnersup: '',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
    ],
  },
  {
    reference: 'winter-div-2',
    href: 'winter-div-2/',
    label: 'Division 2',
    icon: 'fa-battery-half',
    menuSettings: {
      header: true,
      footer: false
    },
    description:
      'Historical winners of the MMPL Winter season in the Second Division.',
    history: [
      {
        season: 2017,
        champion: 'TBC',
        runnersup: 'TBC',
        mvp: '-',
        mvpTeam: '-',
        mvpPlayed: '-',
        mvpWon: '-',
        mvpLost: '-',
      },
      {
        season: 2016,
        champion: 'N/A',
        runnersup: 'N/A',
        mvp: 'N/A',
        mvpTeam: 'N/A',
        mvpPlayed: 'N/A',
        mvpWon: 'N/A',
        mvpLost: 'N/A',
      },
      {
        season: 2015,
        champion: 'Hotel Kew Hawks',
        runnersup: 'Hotham Gold',
        mvp: 'Shane Evans',
        mvpTeam: 'Hotham Gold',
        mvpPlayed: '65',
        mvpWon: '55',
        mvpLost: '10',
      },
      {
        season: 2014,
        champion: 'UC Punters',
        runnersup: 'Royal Derby Tigers',
        mvp: 'Steve Lee',
        mvpTeam: 'Royal Derby Tigers',
        mvpPlayed: '68',
        mvpWon: '51',
        mvpLost: '17',
      },
      {
        season: 2013,
        champion: 'The Ducks',
        runnersup: 'Nomads',
        mvp: 'Darren Johnson',
        mvpTeam: 'Hotham Silver',
        mvpPlayed: '69',
        mvpWon: '50',
        mvpLost: '19',
      },
      {
        season: 2012,
        champion: 'UC Punters',
        runnersup: 'Hotham Gold',
        mvp: 'Greg Tickner',
        mvpTeam: 'Outsiders',
        mvpPlayed: '68',
        mvpWon: '43',
        mvpLost: '25',
      },
      {
        season: 2011,
        champion: 'Ning Nongs',
        runnersup: 'Crown 2',
        mvp: 'Peter Pezzimenti',
        mvpTeam: 'Hulk Smash',
        mvpPlayed: '66',
        mvpWon: '47',
        mvpLost: '19',
      },
      {
        season: 2010,
        champion: 'Hulk Smash',
        runnersup: 'Harpaholics',
        mvp: 'Mark Tarrant',
        mvpTeam: 'Union Club Punters',
        mvpPlayed: '54',
        mvpWon: '39',
        mvpLost: '15',
      },
      {
        season: 2009,
        champion: 'British Crown 3',
        runnersup: 'The Ducks',
        mvp: 'Gus Fleetwood',
        mvpTeam: 'Gold St Gang',
        mvpPlayed: '45',
        mvpWon: '33',
        mvpLost: '12',
      },
      {
        season: 2008,
        champion: 'Coco',
        runnersup: 'Gold Street Gang',
        mvp: 'Al Ogilvy',
        mvpTeam: 'The Ducks',
        mvpPlayed: '54',
        mvpWon: '43',
        mvpLost: '11',
      },
      {
        season: 2007,
        champion: 'The Ning Nongs',
        runnersup: 'Breakers Sharks',
        mvp: 'Matt Ford',
        mvpTeam: 'Ning Nongs',
        mvpPlayed: '38',
        mvpWon: '31',
        mvpLost: '7',
      },
      {
        season: 2006,
        champion: 'Fitzroyalty',
        runnersup: 'The Nash B',
        mvp: 'Matt Purtell',
        mvpTeam: 'The Clare Bears',
        mvpPlayed: '48',
        mvpWon: '37',
        mvpLost: '11',
      },
      {
        season: 2005,
        champion: 'Ning Nongs',
        runnersup: 'Duke Of Windsor',
        mvp: 'Grant Omer',
        mvpTeam: 'Stingo Dragons',
        mvpPlayed: '48',
        mvpWon: '35',
        mvpLost: '13',
      },
      {
        season: 2004,
        champion: 'The Ducks',
        runnersup: 'Rochester Punters',
        mvp: 'Jason Stacy',
        mvpTeam: 'Ning Nongs',
        mvpPlayed: '43',
        mvpWon: '36',
        mvpLost: '7',
      },
      {
        season: 2003,
        champion: 'The Nash Hotel',
        runnersup: 'Rochester Punters',
        mvp: 'George Costaras',
        mvpTeam: 'The Ducks',
        mvpPlayed: '62',
        mvpWon: '44',
        mvpLost: '18',
      },
      {
        season: 2002,
        champion: 'Comics Lounge Growlers',
        runnersup: 'The Nash Hotel',
        mvp: 'Alistair Ogilvy',
        mvpTeam: 'Shot Ducks',
        mvpPlayed: '43',
        mvpWon: '32',
        mvpLost: '11',
      },
      {
        season: 2001,
        champion: 'Powerhouse',
        runnersup: 'Harp Of Erin',
        mvp: 'Steve Juric',
        mvpTeam: 'Powerhouse',
        mvpPlayed: '53',
        mvpWon: '43',
        mvpLost: '10',
      },
      {
        season: 2000,
        champion: 'The Tower Hotel Hawthorn',
        runnersup: 'Whitehorse Inn',
        mvp: 'Jim Liapis',
        mvpTeam: 'Harp Of Erin',
        mvpPlayed: '56',
        mvpWon: '39',
        mvpLost: '17',
      },
      {
        season: 1999,
        champion: 'No 2nd Division before Winter 2000',
        runnersup: '',
        mvp: '',
        mvpTeam: '1999',
        mvpPlayed: 'No 2nd Division before Winter 2000',
        mvpWon: '',
        mvpLost: '',
      },
    ],
  },
  {
    reference: 'winter-div-3',
    href: 'winter-div-3/',
    label: 'Division 3',
    icon: 'fa-battery-quarter',
    menuSettings: {
      header: true,
      footer: false
    },
    description:
      'Historical winners of the MMPL Winter season in the Third Division.',
    history: [
      {
        season: 2010,
        champion: '3rd Division discontinued',
        runnersup: '',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: 2009,
        champion: 'The New Masters',
        runnersup: 'Towering White Knights',
        mvp: 'Jim Little',
        mvpTeam: 'Ramblers',
        mvpPlayed: 41,
        mvpWon: 28,
        mvpLost: 13,
      },
      {
        season: 2008,
        champion: 'Kew & A',
        runnersup: 'Tramway Terminals',
        mvp: 'Chris Mueller &',
        mvpTeam: 'Tramway Terminals',
        mvpPlayed: 41,
        mvpWon: 31,
        mvpLost: 10,
      },
      {
        season: 2008,
        champion: '',
        runnersup: '',
        mvp: 'Dennis McDonald',
        mvpTeam: 'Tower Dragons',
        mvpPlayed: 41,
        mvpWon: 31,
        mvpLost: 10,
      },
      {
        season: 2007,
        champion: 'Harpaholics',
        runnersup: 'Union Club Punters',
        mvp: 'Roland Baglin',
        mvpTeam: 'Harpaholics',
        mvpPlayed: 41,
        mvpWon: 31,
        mvpLost: 10,
      },
      {
        season: 2006,
        champion: 'The Oxford Scholar',
        runnersup: 'DOC Dark Horses',
        mvp: 'Van Ly',
        mvpTeam: 'The Oxford Scholar',
        mvpPlayed: 41,
        mvpWon: 32,
        mvpLost: 9,
      },
      {
        season: 2005,
        champion: 'Yorkshire Turtles',
        runnersup: 'Punters PC',
        mvp: 'John Palmer',
        mvpTeam: 'Dan O\'Connell Dark Horses',
        mvpPlayed: 35,
        mvpWon: 23,
        mvpLost: 12,
      },
      {
        season: 2004,
        champion: 'Tramway Ding Dings',
        runnersup: 'Rochester Punters',
        mvp: 'Tom Maloney',
        mvpTeam: 'The Cue Snowmen',
        mvpPlayed: 35,
        mvpWon: 39,
        mvpLost: 6,
      },
      {
        season: 2003,
        champion: 'Union Club Punters',
        runnersup: 'Francis Green Dragons',
        mvp: 'Alan Boyd',
        mvpTeam: 'Francis Green Dragons',
        mvpPlayed: 46,
        mvpWon: 39,
        mvpLost: 7,
      },
      {
        season: 2002,
        champion: 'Union Club Punters',
        runnersup: 'Francis Hotel',
        mvp: 'Phil Makins',
        mvpTeam: 'Ballbreakers',
        mvpPlayed: 47,
        mvpWon: 34,
        mvpLost: 13,
      },
      {
        season: 2001,
        champion: 'No 3rd Division before Winter 2002',
        runnersup: '',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
    ],
  },
];

export const summerHistory = [
  {
    reference: 'summer-premier',
    href: 'summer-premier/',
    label: 'Premier',
    icon: 'fa-battery-full',
    menuSettings: {
      header: true,
      footer: false
    },
    description:
      'Historical winners of the MMPL Summer season in the Premier Division.',
    history: [
      {
        season: '2016-17',
        champion: 'Quarry Cannons',
        runnersup: 'Baize Invaders',
        mvp: 'Andy Smith',
        mvpTeam: 'Baize Invaders',
        mvpPlayed: 33,
        mvpWon: 27,
        mvpLost: 6,
      },
      {
        season: '2015-16',
        champion: 'Bangers',
        runnersup: 'Baize Invaders',
        mvp: 'Peter Butterworth',
        mvpTeam: 'Bangers',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: '2014-15',
        champion: 'Baize Invaders',
        runnersup: 'Chalks Cheap',
        mvp: 'Andy Smith',
        mvpTeam: 'Baize Invaders',
        mvpPlayed: 36,
        mvpWon: 31,
        mvpLost: 5,
      },
      {
        season: '2013-14',
        champion: 'Baize Invaders',
        runnersup: 'Arcadia',
        mvp: 'James Mifsud',
        mvpTeam: 'Eureka Bangers',
        mvpPlayed: 27,
        mvpWon: 24,
        mvpLost: 3,
      },
      {
        season: '2012-13',
        champion: 'Westerners',
        runnersup: 'The Wombats',
        mvp: 'Tony West',
        mvpTeam: 'Arcadia',
        mvpPlayed: 27,
        mvpWon: 23,
        mvpLost: 4,
      },
      {
        season: '2011-12',
        champion: '59 Bangers',
        runnersup: 'Westerners',
        mvp: 'Peter Butterworth',
        mvpTeam: '59 Bangers',
        mvpPlayed: 28,
        mvpWon: 23,
        mvpLost: 5,
      },
      {
        season: '2010-11',
        champion: '59 Bangers',
        runnersup: 'Westerners',
        mvp: 'James Mifsud',
        mvpTeam: '59 Bangers',
        mvpPlayed: 28,
        mvpWon: 23,
        mvpLost: 5,
      },
      {
        season: '2009-10',
        champion: 'Westerners',
        runnersup: '59 Bangers',
        mvp: 'Steve Tran',
        mvpTeam: 'Westerners',
        mvpPlayed: 32,
        mvpWon: 26,
        mvpLost: 6,
      },
      {
        season: '2008-09',
        champion: '(Station59 V Westerners)',
        runnersup: '',
        mvp: 'Steve Tran',
        mvpTeam: 'Westerners',
        mvpPlayed: 32,
        mvpWon: 27,
        mvpLost: 5,
      },
      {
        season: '2007-08',
        champion: 'Westerners',
        runnersup: 'Bushwhackers',
        mvp: 'Ben Nunan',
        mvpTeam: 'Station59 Bangers',
        mvpPlayed: 36,
        mvpWon: 30,
        mvpLost: 6,
      },
      {
        season: '2006-07',
        champion: 'Westerners',
        runnersup: 'Comics Lounge Cannons',
        mvp: 'Bruce McPhee',
        mvpTeam: 'Legends',
        mvpPlayed: 36,
        mvpWon: 27,
        mvpLost: 9,
      },
      {
        season: '2005-06',
        champion: 'Stingo Cannons',
        runnersup: 'Comics Lounge Bangers',
        mvp: 'Brett Dorrington',
        mvpTeam: 'Stingo Cannons',
        mvpPlayed: 36,
        mvpWon: 27,
        mvpLost: 9,
      },
      {
        season: '2004-05',
        champion: 'Bedford Bangers',
        runnersup: 'The Max Cowboys',
        mvp: 'Ben Nunan',
        mvpTeam: 'Bedford Bangers',
        mvpPlayed: 38,
        mvpWon: 31,
        mvpLost: 7,
      },
      {
        season: '2003-04',
        champion: 'Richmond Cowboys',
        runnersup: 'Waterside Cannons',
        mvp: 'Jim Benis',
        mvpTeam: 'Richmond Cowboys',
        mvpPlayed: 14,
        mvpWon: 13,
        mvpLost: 1,
      },
      {
        season: '2002-03',
        champion: 'Comics Lounge Growlers',
        runnersup: 'Waterside Cannons',
        mvp: 'Gavin Langmaid',
        mvpTeam: 'The Growlers',
        mvpPlayed: 40,
        mvpWon: 30,
        mvpLost: 10,
      },
      {
        season: '2001-02',
        champion: 'Legends A',
        runnersup: 'Waterside Cannons',
        mvp: 'Richard Sheehan',
        mvpTeam: 'Clare Castle',
        mvpPlayed: 42,
        mvpWon: 32,
        mvpLost: 10,
      },
      {
        season: '2000-01',
        champion: 'Breakers',
        runnersup: 'Breakers Black',
        mvp: 'Denis Nikoltsis',
        mvpTeam: 'Breakers',
        mvpPlayed: 39,
        mvpWon: 27,
        mvpLost: 12,
      },
      {
        season: '1999-00',
        champion: 'Clare Castle Hotel',
        runnersup: 'Waterside Tigers',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
    ],
  },
  {
    reference: 'summer-div-1',
    href: 'summer-div-1/',
    label: 'Division 1',
    icon: 'fa-battery-three-quarters',
    menuSettings: {
      header: true,
      footer: false
    },
    description:
      'Historical winners of the MMPL Summer season in the First Division.',
    history: [
      {
        season: '2016-17',
        champion: 'Magnums',
        runnersup: 'Hotel Kew Hawks',
        mvp: 'Jesse McLaren',
        mvpTeam: 'Hotel Kew Hawks',
        mvpPlayed: '24',
        mvpWon: '18',
        mvpLost: '6',
      },
      {
        season: '2015-16',
        champion: 'Unholy Rollers',
        runnersup: 'The Harp Crew',
        mvp: 'Jesse McLaren',
        mvpTeam: 'Hotel Kew Hawks',
        mvpPlayed: '-',
        mvpWon: '-',
        mvpLost: '-',
      },
      {
        season: '2014-15',
        champion: 'The Wombats',
        runnersup: 'Crownies',
        mvp: 'Ash Manocha',
        mvpTeam: 'The Wombats',
        mvpPlayed: '40',
        mvpWon: '32',
        mvpLost: '8',
      },
      {
        season: '2014-15',
        champion: '-',
        runnersup: '-',
        mvp: 'Richard Neville',
        mvpTeam: 'Crownies',
        mvpPlayed: '40',
        mvpWon: '32',
        mvpLost: '8',
      },
      {
        season: '2013-14',
        champion: 'Towering Infernos',
        runnersup: 'Nomads',
        mvp: 'Martin Booth',
        mvpTeam: 'Nomads',
        mvpPlayed: '27',
        mvpWon: '22',
        mvpLost: '5',
      },
      {
        season: '2012-13',
        champion: 'Station Masters',
        runnersup: 'Harpaholics',
        mvp: 'Steve Cresswell',
        mvpTeam: 'Dark Horses',
        mvpPlayed: '32',
        mvpWon: '28',
        mvpLost: '4',
      },
      {
        season: '2011-12',
        champion: 'Fitzroy Punters',
        runnersup: 'Towering Infernos',
        mvp: 'Andy Smith',
        mvpTeam: 'Harpaholics',
        mvpPlayed: '40',
        mvpWon: '33',
        mvpLost: '7',
      },
      {
        season: '2010-11',
        champion: 'Crown 1',
        runnersup: 'OC Convicts',
        mvp: 'Craig Pearson',
        mvpTeam: 'Richmond Cowboys',
        mvpPlayed: '36',
        mvpWon: '30',
        mvpLost: '6',
      },
      {
        season: '2009-10',
        champion: 'Fitzroyalty',
        runnersup: 'The Ducks',
        mvp: 'David Saab',
        mvpTeam: 'British Crown 1',
        mvpPlayed: '34',
        mvpWon: '27',
        mvpLost: '7',
      },
      {
        season: '2008-09',
        champion: '(Oxford Scholar V Gypsy Punters)',
        runnersup: '',
        mvp: 'Sam Crunden-Peck',
        mvpTeam: 'The Oxford Scholar',
        mvpPlayed: '36',
        mvpWon: '28',
        mvpLost: '8',
      },
      {
        season: '2007-08',
        champion: 'Inkerman Cowboys',
        runnersup: 'Royal Mail Wombats',
        mvp: 'David Kelly',
        mvpTeam: 'Royal Mail Wombats',
        mvpPlayed: '27',
        mvpWon: '21',
        mvpLost: '6',
      },
      {
        season: '2006-07',
        champion: 'Old Colonial Punters',
        runnersup: 'Tower Assassins',
        mvp: 'Milton White',
        mvpTeam: 'Old Colonial Punters B',
        mvpPlayed: '33',
        mvpWon: '24',
        mvpLost: '9',
      },
      {
        season: '2005-06',
        champion: 'The Dick Cowboys',
        runnersup: 'Rochester Punters',
        mvp: 'Kevin Lehane',
        mvpTeam: 'The Dick Cowboys',
        mvpPlayed: '36',
        mvpWon: '26',
        mvpLost: '10',
      },
      {
        season: '2004-05',
        champion: 'Rochester Punters',
        runnersup: 'The Wombats',
        mvp: 'Brenden Dominguez',
        mvpTeam: 'Tramway',
        mvpPlayed: '45',
        mvpWon: '30',
        mvpLost: '15',
      },
      {
        season: '2003-04',
        champion: 'Fitzroy Diehards',
        runnersup: 'Tramway Hotel',
        mvp: 'Paul Holmes',
        mvpTeam: 'Rochester Punters',
        mvpPlayed: '35',
        mvpWon: '26',
        mvpLost: '9',
      },
      {
        season: '2002-03',
        champion: 'The Distant Cue',
        runnersup: 'Fitzroy Diehards',
        mvp: 'Stuart Morriss',
        mvpTeam: 'Fitzroy Diehards',
        mvpPlayed: '30',
        mvpWon: '23',
        mvpLost: '7',
      },
      {
        season: '2001-02*',
        champion: 'The Nash Dudes*',
        runnersup: '(Whitehorse Inn)*',
        mvp: 'Jaye Allan-Dayle',
        mvpTeam: 'Nash Dudes',
        mvpPlayed: '48',
        mvpWon: '37',
        mvpLost: '11',
      },
      {
        season: '2000-01',
        champion: 'Harp of Erin',
        runnersup: 'Nash Hotel',
        mvp: 'Dean Power',
        mvpTeam: 'Powerhouse',
        mvpPlayed: '28',
        mvpWon: '24',
        mvpLost: '4',
      },
      {
        season: '1999-00*',
        champion: 'Powerhouse*',
        runnersup: '(Ballbreakers)*',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: '',
        mvpWon: '',
        mvpLost: '',
      },
    ],
  },
  {
    reference: 'summer-div-2',
    href: 'summer-div-2/',
    label: 'Division 2',
    icon: 'fa-battery-half',
    menuSettings: {
      header: true,
      footer: false
    },
    description:
      'Historical winners of the MMPL Summer season in the Second Division.',
    history: [
      {
        season: '2015-16',
        champion: 'No 2nd Division This Summer',
        runnersup: '',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: '2014-15',
        champion: 'Loose Cannons',
        runnersup: 'Gold Street Gang',
        mvp: 'Newman Pinto',
        mvpTeam: 'The Harp Crew',
        mvpPlayed: 40,
        mvpWon: 29,
        mvpLost: 11,
      },
      {
        season: '2013-14',
        champion: 'Uc Punters',
        runnersup: 'Hotham Gold',
        mvp: 'Mark Holly',
        mvpTeam: 'Hotham Gold',
        mvpPlayed: 36,
        mvpWon: 27,
        mvpLost: 9,
      },
      {
        season: '2012-13',
        champion: 'No 2nd Division This Summer',
        runnersup: '',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
      {
        season: '2011-12',
        champion: 'Hotham Gold',
        runnersup: 'Ppc Bc2',
        mvp: 'Mark Holly',
        mvpTeam: 'Hotham Gold',
        mvpPlayed: 41,
        mvpWon: 29,
        mvpLost: 12,
      },
      {
        season: '2010-11',
        champion: 'Uc Punters',
        runnersup: 'Hulk Smash',
        mvp: 'Will Reeves',
        mvpTeam: '8 Balls Of Fire',
        mvpPlayed: 30,
        mvpWon: 23,
        mvpLost: 7,
      },
      {
        season: '2009-10',
        champion: 'Palookavillains',
        runnersup: 'Uc Punters',
        mvp: 'Paul Holmes',
        mvpTeam: 'Palookavillains',
        mvpPlayed: 28,
        mvpWon: 24,
        mvpLost: 4,
      },
      {
        season: '2008-09',
        champion: '(Yarra Sharks V Uc Punters)',
        runnersup: '',
        mvp: 'Timo Pekkarinen',
        mvpTeam: 'Yarra Sharks',
        mvpPlayed: 36,
        mvpWon: 29,
        mvpLost: 7,
      },
      {
        season: '2007-08',
        champion: 'Harpaholics B',
        runnersup: 'Cue Tang Clan',
        mvp: 'Ken Wakeman',
        mvpTeam: 'Cue-Tang Clan',
        mvpPlayed: 31,
        mvpWon: 27,
        mvpLost: 4,
      },
      {
        season: '2006-07',
        champion: 'Breakers Sharks',
        runnersup: 'The Ox',
        mvp: 'Wade Stephens',
        mvpTeam: 'The Oxford Scholar',
        mvpPlayed: 21,
        mvpWon: 18,
        mvpLost: 3,
      },
      {
        season: '2005-06',
        champion: 'Legends B',
        runnersup: 'Fitzroyalty',
        mvp: 'Frank Brandi',
        mvpTeam: 'The Cue Masters',
        mvpPlayed: 35,
        mvpWon: 27,
        mvpLost: 8,
      },
      {
        season: '2004-05',
        champion: 'Whitehorse Wyld Stalyns',
        runnersup: 'Harp Odd Bods',
        mvp: 'Blair Wickens',
        mvpTeam: 'Yorkshire Dragons',
        mvpPlayed: 41,
        mvpWon: 27,
        mvpLost: 14,
      },
      {
        season: '2003-04',
        champion: 'Union Club Punters',
        runnersup: 'Duke Of Windsor',
        mvp: 'Michael Drozdowski',
        mvpTeam: 'Fitzroy Pool Explosion',
        mvpPlayed: 25,
        mvpWon: 18,
        mvpLost: 7,
      },
      {
        season: '2002-03',
        champion: 'Rochester Punters',
        runnersup: 'Kp&The Sunshine Band',
        mvp: 'Eli Bateman',
        mvpTeam: 'Rochester Punters',
        mvpPlayed: 41,
        mvpWon: 30,
        mvpLost: 11,
      },
      {
        season: '2001-02*',
        champion: '(The Nash Dudes)*',
        runnersup: '(Whitehorse Inn)*',
        mvp: 'Patrick Willemyns',
        mvpTeam: 'Whitehorse Inn',
        mvpPlayed: 41,
        mvpWon: 31,
        mvpLost: 10,
      },
      {
        season: '2000-01',
        champion: 'Parkview Ning Nongs',
        runnersup: 'Vella Allstars',
        mvp: 'Mark Ludgrove',
        mvpTeam: 'Duke Of Windsor',
        mvpPlayed: 37,
        mvpWon: 28,
        mvpLost: 9,
      },
      {
        season: '1999-00*',
        champion: '(Powerhouse)*',
        runnersup: '(Ballbreakers)*',
        mvp: '',
        mvpTeam: '',
        mvpPlayed: null,
        mvpWon: null,
        mvpLost: null,
      },
    ],
  },
];
